### ISSUE TITLE
An update

### ISSUE THREAD

**Issue by viktorprogger** [MilesChou/docker-xdebug#4]
Please build new images to use new php versions. One of projects I work on requires php version 7.4.7 and above becase `yield from` is bronken in 7.4.6.

Thank you in advance!

**Comment by MilesChou** [comment]
Re-run actions on a1e1ac5b9e9a6c3d79eda20c594e58cd24e4f2b8 commit

<img width="941" src="https://user-images.githubusercontent.com/1258752/91274855-e5de4c00-e7b1-11ea-9d06-ca59d7ef1fe1.png">

**Comment by viktorprogger** [comment]
Thank you very much!
