### ISSUE TITLE
Failed to pull image in Gitlab CI/CD pipeline

### ISSUE THREAD

**Issue by xfudox** [MilesChou/docker-xdebug#5]
Hi, i've just added your PHP+Xdebug docker image to my pipeline but i get this error using `mileschou/xdebug:8.0`.

The weirdest part is that my pipeline runs 3 parallel jobs to test my code against php 7.3, 7.4 and 8.0, and i get no errors on the 7.3 and 7.4 testing jobs, which uses your image as well.

Do i need to add some specifi configuration to run the 8.0 image?

![image](https://user-images.githubusercontent.com/9081531/112130915-41967980-8bc9-11eb-89f2-25b390e1eaae.png)

**Comment by MilesChou** [comment]
I didn't push image on Dockerhub, and I push just recently.

Alternatively, use GitHub Registry.

https://github.com/users/MilesChou/packages/container/package/xdebug

**Comment by xfudox** [comment]
Thanks, i confirm that now the images is correctly pulled.
