### ISSUE TITLE
7.3 image not getting XDEBUG_MODE env variable

### ISSUE THREAD

**Issue by xfudox** [MilesChou/docker-xdebug#6]
I'm using the 7.3 image in my Gitlab pipeline but it seems not getting the `XDEBUG_MODE` environment variable.

As you can see on line 32 of my pipeline output i correctly set the variable, but at line 37 i get a Xdebug warning that states the opposite.

I'm also using the 7.4 image in the same pipeline to test my code against php 7.4 as well, and in that job i don't get any issue; moreover 7.4 image seems not needing my env variable setting, it works correctly outside of the box.

I took a look at both Dockerfile on Github, but they are identical except for php version, so i cannot figure out why i'm getting these different behaviours.

![image](https://user-images.githubusercontent.com/9081531/112156351-77962680-8be6-11eb-988d-0fa246258827.png)

**Comment by MilesChou** [comment]
try use `export` instead `set`, or set env before phpunit command, or add `-d` option:

```
export XDEBUG_MODE=coverage

# or

XDEBUG_MODE=coverage php vendor/bin/phpunit

# or

php -dxdebug.mode=coverage vendor/bin/phpunit
```

**Comment by xfudox** [comment]
Thanks again,
`php -dxdebug.mode=coverage vendor/bin/phpunit`
solved the problem.
